// This is program-generated source. Do no changes in it!
// Sakhnik, 2003

#ifndef _INTERFACE
#define _INTERFACE

#define TOTAL_GUI_ITEMS_COUNT 310
#define DRAW_QUEUE_MAX 8
#define DIALOG_STACK_MAX 7

// You should pick up this parameter experimentally, so that the repainting
// was the most efficient
#define MAX_ITEMS_TO_DRAW 25

enum GUIItemKind
{
	IDK_NOTHING,
	IDK_BEGIN,
	IDK_END,

	IDK_DIALOG,

	IDK_TABCONTROL,
	IDK_TAB,
	IDK_LABEL,
	IDK_EDIT,
	IDK_BUTTON,
	IDK_CHECK,
	IDK_BMP,
	IDK_TABLE
};

// GUI Item's IDs
#define ID_NULL 0

#define ID_SPLASH_FORMSPLASH	1
#define ID_MACHINE_FORMMACHINE	2
#define ID_INJECTION_FORMINJECTION	3
#define ID_LOCK_FORMLOCK	4
#define ID_TEMPERATURE_FORMT	5
#define ID_TEST_FORMTEST	6
#define ID_TEST_L0	8
#define ID_TEST_LTEST	9
#define ID_TEST_L1	10
#define ID_TEST_L2	11
#define ID_TEST_L3	12
#define ID_TEST_L4	13
#define ID_TEST_L5	14
#define ID_TEST_L6	15
#define ID_TEST_L7	16
#define ID_TEST_IMG00	17
#define ID_TEST_IMG10	18
#define ID_TEST_IMG20	19
#define ID_TEST_IMG40	20
#define ID_TEST_IMG30	21
#define ID_TEST_LVERSION	22
#define ID_TEST_LNAME	23
#define ID_TEST_LEMAIL	24
#define ID_TEST_LURL	25
#define ID_TEST_LAUTHOR	26
#define ID_TEST_LAUTHORSEMAIL	27
#define ID_TEST_LCITY	28
#define ID_TEST_IMG50	29
#define ID_TEST_IMGEXIT	30
#define ID_TEST_CBIN00	31
#define ID_TEST_CBIN01	32
#define ID_TEST_CBIN02	33
#define ID_TEST_CBIN03	34
#define ID_TEST_CBIN04	35
#define ID_TEST_CBIN05	36
#define ID_TEST_CBIN06	37
#define ID_TEST_CBIN07	38
#define ID_TEST_CBIN10	39
#define ID_TEST_CBIN11	40
#define ID_TEST_CBIN12	41
#define ID_TEST_CBIN13	42
#define ID_TEST_CBIN14	43
#define ID_TEST_CBIN15	44
#define ID_TEST_CBIN17	45
#define ID_TEST_CBIN16	46
#define ID_TEST_CBIN20	47
#define ID_TEST_CBIN21	48
#define ID_TEST_CBIN22	49
#define ID_TEST_CBIN23	50
#define ID_TEST_CBIN24	51
#define ID_TEST_CBIN25	52
#define ID_TEST_CBIN27	53
#define ID_TEST_CBIN26	54
#define ID_TEST_CBIN30	55
#define ID_TEST_CBIN31	56
#define ID_TEST_CBIN32	57
#define ID_TEST_CBIN33	58
#define ID_TEST_CBIN34	59
#define ID_TEST_CBIN35	60
#define ID_TEST_CBIN37	61
#define ID_TEST_CBIN36	62
#define ID_TEST_CBIN40	63
#define ID_TEST_CBIN41	64
#define ID_TEST_CBIN42	65
#define ID_TEST_CBIN43	66
#define ID_TEST_CBIN44	67
#define ID_TEST_CBIN45	68
#define ID_TEST_CBIN47	69
#define ID_TEST_CBIN46	70
#define ID_TEST_BTESTOUT	71
#define ID_TEST_CBIN50	72
#define ID_TEST_CBIN51	73
#define ID_TEST_CBIN52	74
#define ID_TEST_CBIN53	75
#define ID_TEST_CBIN54	76
#define ID_TEST_CBIN55	77
#define ID_TEST_CBIN56	78
#define ID_TEST_CBIN57	79
#define ID_TEST_BEXIT	80
#define ID_TEMPERATURE_LTEMPERATURE	82
#define ID_TEMPERATURE_LC1	83
#define ID_TEMPERATURE_LC2	84
#define ID_TEMPERATURE_LC3	85
#define ID_TEMPERATURE_LC4	86
#define ID_TEMPERATURE_LC5	87
#define ID_TEMPERATURE_LC6	88
#define ID_TEMPERATURE_LC7	89
#define ID_TEMPERATURE_LC8	90
#define ID_TEMPERATURE_LCA	91
#define ID_TEMPERATURE_LT	92
#define ID_TEMPERATURE_IMGMD	93
#define ID_TEMPERATURE_IMGPD	94
#define ID_TEMPERATURE_IMGTS	95
#define ID_TEMPERATURE_LMINOILT	96
#define ID_TEMPERATURE_LOILCOOLT	97
#define ID_TEMPERATURE_IMGPID	98
#define ID_TEMPERATURE_IMGEXIT	99
#define ID_TEMPERATURE_EC1T	100
#define ID_TEMPERATURE_EC2T	101
#define ID_TEMPERATURE_EC3T	102
#define ID_TEMPERATURE_EC4T	103
#define ID_TEMPERATURE_EC5T	104
#define ID_TEMPERATURE_EC6T	105
#define ID_TEMPERATURE_EC7T	106
#define ID_TEMPERATURE_EC8T	107
#define ID_TEMPERATURE_ECAT	108
#define ID_TEMPERATURE_EC1MDT	109
#define ID_TEMPERATURE_EC1PDT	110
#define ID_TEMPERATURE_EC2MDT	111
#define ID_TEMPERATURE_EC3MDT	112
#define ID_TEMPERATURE_EC8PDT	113
#define ID_TEMPERATURE_ECAPDT	114
#define ID_TEMPERATURE_EC4MDT	115
#define ID_TEMPERATURE_EC2PDT	116
#define ID_TEMPERATURE_EC5MDT	117
#define ID_TEMPERATURE_EC3PDT	118
#define ID_TEMPERATURE_EC6MDT	119
#define ID_TEMPERATURE_EC4PDT	120
#define ID_TEMPERATURE_EC7MDT	121
#define ID_TEMPERATURE_EC5PDT	122
#define ID_TEMPERATURE_EC8MDT	123
#define ID_TEMPERATURE_EC6PDT	124
#define ID_TEMPERATURE_ECAMDT	125
#define ID_TEMPERATURE_EC7PDT	126
#define ID_TEMPERATURE_EC1TS	127
#define ID_TEMPERATURE_EC2TS	128
#define ID_TEMPERATURE_EC3TS	129
#define ID_TEMPERATURE_EC4TS	130
#define ID_TEMPERATURE_EC5TS	131
#define ID_TEMPERATURE_EC6TS	132
#define ID_TEMPERATURE_EC7TS	133
#define ID_TEMPERATURE_EC8TS	134
#define ID_TEMPERATURE_ECATS	135
#define ID_TEMPERATURE_EMINOILT	136
#define ID_TEMPERATURE_EOILCOOLT	137
#define ID_TEMPERATURE_BPID	138
#define ID_TEMPERATURE_BEXIT	139
#define ID_LOCK_LTITLE	141
#define ID_LOCK_LQ	142
#define ID_LOCK_LSTART	143
#define ID_LOCK_LACCEL1	144
#define ID_LOCK_LPROTECTION	145
#define ID_LOCK_LFULLLOCK	146
#define ID_LOCK_LSTART1	147
#define ID_LOCK_LACCEL	148
#define ID_LOCK_LDECEL	149
#define ID_LOCK_IMGDX	150
#define ID_LOCK_LDEGAS	151
#define ID_LOCK_LCONTRLOCKTIME	152
#define ID_LOCK_LPUSHMOV	153
#define ID_LOCK_LCHOPMOV	154
#define ID_LOCK_LRETCHOP	155
#define ID_LOCK_IMGCLOCK	156
#define ID_LOCK_IMGLOCK	157
#define ID_LOCK_LCHOPMOVES	158
#define ID_LOCK_IMGHELP	159
#define ID_LOCK_IMGEXIT	160
#define ID_LOCK_ESTARTQ	161
#define ID_LOCK_EACCELQ	162
#define ID_LOCK_EPROTECTQ	163
#define ID_LOCK_EFULLLOCKQ	164
#define ID_LOCK_EACCELQ2	165
#define ID_LOCK_ESTARTQ2	166
#define ID_LOCK_ESTARTX	167
#define ID_LOCK_EACCELX	168
#define ID_LOCK_EPROTECTX	169
#define ID_LOCK_EFULLLOCKX	170
#define ID_LOCK_ESTARTX2	171
#define ID_LOCK_EACCELX2	172
#define ID_LOCK_EDECELQ	173
#define ID_LOCK_EDECELX	174
#define ID_LOCK_EMOVDROPQ	175
#define ID_LOCK_EMOVDROPX	176
#define ID_LOCK_EBACKDOWNQ	177
#define ID_LOCK_EBACKDOWNX	178
#define ID_LOCK_EDEGASX	179
#define ID_LOCK_EDEGAST	180
#define ID_LOCK_EPUSHMOV	181
#define ID_LOCK_ETIMETESTT	182
#define ID_LOCK_CBDIF	183
#define ID_LOCK_BEXIT	184
#define ID_LOCK_ECHOPMOV	185
#define ID_LOCK_BHELP	186
#define ID_INJECTION_LINJECTION	188
#define ID_INJECTION_LINJ1	189
#define ID_INJECTION_LINJ2	190
#define ID_INJECTION_LINJ3	191
#define ID_INJECTION_LQ	192
#define ID_INJECTION_LT	193
#define ID_INJECTION_IMGDX	194
#define ID_INJECTION_LLOAD1	195
#define ID_INJECTION_LLOAD2	196
#define ID_INJECTION_LLOAD3	197
#define ID_INJECTION_LFORM1	198
#define ID_INJECTION_LFORM2	199
#define ID_INJECTION_LDECOMPRESSION	200
#define ID_INJECTION_IMGEXIT	201
#define ID_INJECTION_EINJ1Q	202
#define ID_INJECTION_EINJ2Q	203
#define ID_INJECTION_EINJ3Q	204
#define ID_INJECTION_EFOR1Q	205
#define ID_INJECTION_EFOR2Q	206
#define ID_INJECTION_ELOAD1Q	207
#define ID_INJECTION_ELOAD2Q	208
#define ID_INJECTION_ELOAD3Q	209
#define ID_INJECTION_EDECOMPQ	210
#define ID_INJECTION_EINJT	211
#define ID_INJECTION_EFOR1T	212
#define ID_INJECTION_EFOR2T	213
#define ID_INJECTION_EDECOMPT	214
#define ID_INJECTION_ELOADT	215
#define ID_INJECTION_EINJ1X	216
#define ID_INJECTION_EINJ3X	217
#define ID_INJECTION_EFOR1X	218
#define ID_INJECTION_EFOR2X	219
#define ID_INJECTION_ELOAD1X	220
#define ID_INJECTION_ELOAD2X	221
#define ID_INJECTION_ELOAD3X	222
#define ID_INJECTION_EDECOMPX	223
#define ID_INJECTION_EINJ2X	224
#define ID_INJECTION_BEXIT	225
#define ID_MACHINE_IMGPLATE1_1	227
#define ID_MACHINE_IMGPLATE1_2	228
#define ID_MACHINE_IMGPLATE1_3	229
#define ID_MACHINE_IMGPLATE2	230
#define ID_MACHINE_IMGCANON	231
#define ID_MACHINE_IMGSCREW	232
#define ID_MACHINE_LT4	233
#define ID_MACHINE_LT3	234
#define ID_MACHINE_LT2	235
#define ID_MACHINE_LDX1	236
#define ID_MACHINE_LDX3	237
#define ID_MACHINE_LDT4	238
#define ID_MACHINE_LDT3	239
#define ID_MACHINE_LDT2	240
#define ID_MACHINE_LDT1	241
#define ID_MACHINE_LTS4	242
#define ID_MACHINE_LTS3	243
#define ID_MACHINE_LTS2	244
#define ID_MACHINE_LTS1	245
#define ID_MACHINE_IMG31	246
#define ID_MACHINE_IMG32	247
#define ID_MACHINE_IMG33	248
#define ID_MACHINE_IMG36	249
#define ID_MACHINE_IMG35	250
#define ID_MACHINE_IMG34	251
#define ID_MACHINE_IMG8	252
#define ID_MACHINE_IMG9	253
#define ID_MACHINE_IMG28	254
#define ID_MACHINE_IMG13	255
#define ID_MACHINE_LTOTAL	256
#define ID_MACHINE_LTCOUNT	257
#define ID_MACHINE_IMGELIMINATOR	258
#define ID_MACHINE_IMGOIL	259
#define ID_MACHINE_LOIL	260
#define ID_MACHINE_LTS5	261
#define ID_MACHINE_LDT5	262
#define ID_MACHINE_LT5	263
#define ID_MACHINE_LTS6	264
#define ID_MACHINE_LDT6	265
#define ID_MACHINE_LT6	266
#define ID_MACHINE_LTS7	267
#define ID_MACHINE_LDT7	268
#define ID_MACHINE_LT7	269
#define ID_MACHINE_LT1	270
#define ID_MACHINE_LN7	271
#define ID_MACHINE_LN6	272
#define ID_MACHINE_LN5	273
#define ID_MACHINE_LN4	274
#define ID_MACHINE_LN3	275
#define ID_MACHINE_LN2	276
#define ID_MACHINE_LN1	277
#define ID_MACHINE_IMG12	278
#define ID_MACHINE_IMG6	279
#define ID_MACHINE_IMG5	280
#define ID_MACHINE_IMG3	281
#define ID_MACHINE_IMG4	282
#define ID_MACHINE_IMG37	283
#define ID_MACHINE_IMG38	284
#define ID_MACHINE_IMGCLOCK	285
#define ID_MACHINE_LCLOCK	286
#define ID_MACHINE_IMGINJECTION	287
#define ID_MACHINE_IMGLOCK	288
#define ID_MACHINE_IMGTHERMO	289
#define ID_MACHINE_IMGTEST	290
#define ID_MACHINE_IMG2	291
#define ID_MACHINE_IMG1	292
#define ID_MACHINE_IMG10	293
#define ID_MACHINE_IMG14	294
#define ID_MACHINE_IMGHELP	295
#define ID_MACHINE_LMESSAGE	296
#define ID_MACHINE_IMGPANEL	297
#define ID_MACHINE_IMGPROP	298
#define ID_MACHINE_IMG1_1	299
#define ID_MACHINE_BINJECTION	300
#define ID_MACHINE_BLOCK	301
#define ID_MACHINE_BTHERMO	302
#define ID_MACHINE_BTEST	303
#define ID_MACHINE_BHELP	304
#define ID_MACHINE_BPROP	305
#define ID_SPLASH_IMGSPLASH	307


struct CAdditionalData
{
	char IsEnabled:1;
	char IsVisible:1;
	char IsExtra:1;
};

struct CGUIConstItem
{
	enum GUIItemKind Kind; // Type of Item or Container
	int ID; //This field is used in user part for identification
	const unsigned int Left, Top, Width, Height; // Geometrical parameters in screen coordinates.
					// Best works if Left and Width are divisible by 4
	const unsigned char *Caption;
	const unsigned char *Tip;
	const struct CGUIConstItem *Contained; // First Item in this Container
	const struct CGUIConstItem *Owner; // The container of the Item or of this Container
	struct CAdditionalData *Additional; // Other changeable data
	void *Specific;  // Specific information for every ItemKind, it allocates in the RAM and can be modified during execution
};

struct CTabControlItem
{
	const struct CGUIConstItem *First; // First visible Tab
	const struct CGUIConstItem *Active; // Active Tab
};

struct CEditBoxItem
{
	unsigned char *Text;
	char CharactersReserved;
};

struct CCheckBoxItem
{
	char IsChecked;
};

struct CBmpItem
{
	unsigned int Left,Top;
};

struct CTableCtrl
{
	unsigned char ColCount,RowCount;
};

struct CDialogCtrl
{
	const struct CGUIConstItem *Cursor;
};

extern const struct CGUIConstItem ConstDeskTop[TOTAL_GUI_ITEMS_COUNT];

#endif
// End of iface.h
